baseURL = "https://preslav.me/"
languageCode = "en-us"
title = "Preslav Rachev"
theme = "my-ananke"
pygmentsCodeFences=true
disqusShortname = "preslav"
googleAnalytics = "UA-131031623-1"
enableRobotsTXT = true

[Author]
  name = "Preslav Rachev"
  description = "I am a software engineer at KI labs GmbH and advocate for strong developer culture. In my free time, I enjoy running in the woods, reading a great book, or working on my next piece of writing/music."

[permalinks]
  post = "/:year/:month/:day/:filename/"

[outputs]
  page = ["HTML", "AMP"]

[outputFormats]
 [outputFormats.AMP]
    permalinkable = false

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "microblog"
    name = "Microblog"
    url = "/microblog/"
    weight = 20
  
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 30

[params]
    description = "I am a software engineer fighting data science, a marathon-wannabe, a hobby musician, a voracious reader, and photographer. I mostly write about building a strong developer culture."
    featured_image = "https://images.unsplash.com/photo-1553640627-57a6de3bf0ff?ixlib=rb-1.2.1&auto=format&fit=crop&w=1280&q=80"
    recent_posts_number = 10
    custom_css = ["css/styles.css", "css/cookieconsent.min.css"]
    mainSections = ["post", "microblog"]
    show_reading_time = true
    show_related = true
    twitter = "https://twitter.com/preslavrachev"
    github = "https://github.com/preslavrachev"
    clicky_analytics = "101131786"
    header_ctas = [
      "Dear reader, this website is undergoing active migration. Apologies for the temporary inconvenience.",
      "Have an improvement request? Drop me a <a href=\"#disqus_thread\">comment down below</a>, or <a href=\"/contact/\">contact me.</a>",
      "Psst, you might wanna check out the <a href=\"/microblog/\">\"Microblog\"</a> section I've created recently. <a href=\"/contact/\">Let me know</a> what you think"
    ]

[caches]
  [caches.getjson]
  dir = ":resourceDir/_gen"
  maxAge = -1

[related]
threshold = 80
includeNewer = true
toLower = true
[[related.indices]]
    name = "tags"
    weight = 100
[[related.indices]]
    name = "categories"
    weight = 10
