baseURL = "https://preslav.me"
title = "Random Bits of Wisdom"
author = "Preslav Rachev"
# copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "casper3"
googleAnalytics = "UA-131031623-1"

[params]
  #facebook = "https://facebook.com"
  twitter = "https://twitter.com/preslavrachev"
  github = "https://github.com/preslavrachev"
  description = "I am a software engineer building his own stuff. This is my home on the Internet."
  mainSections = ["post"]

  # Metadata mostly used in document's head
  #description = "I am a software engineer at KI labs GmbH and advocate for strong developer culture. In my free time, I enjoy running in the woods, reading a great book, or working on my next piece of writing/music."
  keywords = "programming, golang, python, elixir"

[permalinks]
  post = "/:year/:month/:day/:filename/"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About Me"
    url        = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects/"
    weight = 20
  [[menu.main]]
    identifier = "privacy"
    name       = "Privacy"
    url        = "/privacy/"
    weight = 30
  [[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight = 40

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

[caches]
  [caches.getjson]
  dir = ":resourceDir/_gen"
  maxAge = -1

[outputs]
  page = ["HTML", "AMP"]

[outputFormats]
 [outputFormats.AMP]
    permalinkable = false