version: 2
jobs:
  build:
    branches:
      only:
        - release
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      # install git
      - run: apk update && apk add git zip

      # checkout the repository
      - checkout

      - run: git config user.email "rachev.preslav@gmail.com"
      - run: git config user.name "Preslav Rachev"

      # install git submodules for managing third-party dependencies
      - run: git submodule sync && git submodule update --init

      # build with Hugo
      - run: git worktree add -B gh-pages $HUGO_BUILD_DIR origin/gh-pages
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR

      - run:
          name: Generate a ZIP artifact
          command: |
            zip -r myblog.zip $HUGO_BUILD_DIR

      - run:
          name: Deploy
          command: |
            cd $HUGO_BUILD_DIR
            git add .
            git commit -m "Publishing to gh-pages"
            cd ..
            git push origin gh-pages

      - store_artifacts:
          path: ./myblog.zip
          destination: myblog.zip
