version: 2
jobs:
  build:
    branches:
      only:
        - release
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      # install git
      - run: apk update && apk add git

      # checkout the repository
      - checkout

      # install git submodules for managing third-party dependencies
      - run: git submodule sync && git submodule update --init

      # build with Hugo
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR

      - run:
          name: Generate a ZIP artifact
          command: |
            zip -r myblog.zip $HUGO_BUILD_DIR

      - store_artifacts:
          path: ./myblog.zip
          destination: myblog.zip
